name: CD

on:
    push:
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "cd"
    cancel-in-progress: true

jobs:
    docs:
        name: Docs
        runs-on: ubuntu-latest
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build docs
              run: yarn docs

            - name: Setup pages
              uses: actions/configure-pages@v4

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./docs"

            - name: Deploy pages
              id: deployment
              uses: actions/deploy-pages@v4
